apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ui-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.ui.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.ui.service.name }}
          servicePort: {{ .Values.ui.service.externalPort }}
