kind: Service
apiVersion: v1
metadata:
  name: rabbit-service
spec:
  type: ClusterIP
  selector:
    app: rabbit
  ports:
  - port: 5672
    targetPort: 5672
  - port: 15672
    targetPort: 15672
