apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: mamontov/ui:v1
        env:
        - name: MONGO
          value: "mongo-service"
        - name: MONGO_PORT
          value: "27017"
        command: ["FLASK_APP=ui.py gunicorn ui:app -b 0.0.0.0"]
        ports:
        - containerPort: 8000
